
clc; clear; close all; 

orbitType = 'QB50orbit';
mission.mdl = "CubesatDynamicsModel_complex";
Resultspath = 'Data/QB50/';

% Define global parameters  
Earth.mu = 3.986*10^14;      % Gravitational parameter of Earth [m^3/s^2]
Earth.radius = 6378*10^3;    % Radius of Earth [m]

% Keplerian orbital elements for the CubeSat at the mission.StartDate.
mission.CubeSat.EpochDate        = datetime(2014, 6, 15, 12, 0, 0);
mission.CubeSat.Altitude         = 330*10^3;
mission.CubeSat.SemiMajorAxis    = Earth.radius + mission.CubeSat.Altitude; % [m]
mission.CubeSat.Eccentricity     = 0; % [-]
mission.CubeSat.Inclination      = 79; % [deg]
mission.CubeSat.RAAN             = 250;  % [deg]
mission.CubeSat.ArgOfPeriapsis   = 0; % [deg]
mission.CubeSat.TrueAnomaly      = 84; % [deg]
mission.CubeSat.ArgOfLattitude   = 0; % [deg]

% Characteristics of the cubesat
mission.CubeSat.m  = 2;        % [kg]
mission.CubeSat.A  = 0.01667;  % [m2]
mission.CubeSat.I  = eye(3);


% Define simulation for 2 orbits
mission.StartDate = datetime(2014, 6, 15, 12, 0, 0);
mission.Period    = 2*pi*sqrt(mission.CubeSat.SemiMajorAxis^3/Earth.mu); %[s]
mission.Duration  = hours(mission.Period/3600);
mission.EndDate   = mission.StartDate + mission.Duration;
mission.Timestep  = 0.5;

% Open simulaiton
open_system(mission.mdl);

% Define the path to the Spacecraft dynamics block in the model.
mission.CubeSat.blk = mission.mdl + "/Spacecraft Dynamics";

% DEFINE PARAMETERS 

% MAIN
set_param(mission.CubeSat.blk, ...
    forcesin     = "off", ...
    momentsIn    = "on",...
    accelIn      = "off",...
    accelFrame   = "Fixed-frame",...
    outportFrame = "Fixed-frame",...
    outputAccel  = "on", ...
    startDate    = num2str(juliandate(mission.StartDate)), ...
    dateOut      = "on", ...
    action       = "Warning");

% MASS
set_param(mission.CubeSat.blk, ...
    massType = "Fixed", ...
    mass     = "mission.CubeSat.m",...
    inertia  = "mission.CubeSat.I");

% ORBIT
set_param(mission.CubeSat.blk, ...
    stateFormatNum   = "Orbital elements",...
    orbitType        = "Keplerian", ...
    semiMajorAxis    = "mission.CubeSat.SemiMajorAxis", ...
    eccentricity     = "mission.CubeSat.Eccentricity", ...
    inclination      = "mission.CubeSat.Inclination", ...
    raan             = "mission.CubeSat.RAAN", ...
    argPeriapsis     = "mission.CubeSat.ArgOfPeriapsis", ...
    trueAnomaly      = "mission.CubeSat.TrueAnomaly");

% ATTITUDE: 
set_param(mission.CubeSat.blk, ...
    attitudeFrame   = "ICRF",...
    attitudeFormat  = "Quaternion",...
    attitude        = "[0.5963 -0.1096 -0.4052 0.6842]",...
    rotationOrder   = "ZYX",...
    attitudeRate    = "[0, 0, 0]",...
    outputAngAccel  = "on",...
    useGravGrad     = "on");

% CENTRAL BODY: 
set_param(mission.CubeSat.blk, ...
    centralBody     = "Earth",...
    gravityModel    = "Spherical harmonics",...
    earthSH         = "EGM2008",...
    shDegree        = "120", ...
    useEOPs         = "on",...
    eopFile         = "aeroiersdata.mat",...
    outputTransform = "on");

% DRAG
set_param(mission.CubeSat.blk, ...
    useDrag                   = "on",...
    atmosSrc                  = "Dialog",...
    atmosModel                = "NRLMSISE-00", ...
    fluxSrc                   = "Dialog",...
    SpaceWeatherDataFile      = "aeroSpaceWeatherData.mat", ...
    F107ExtrapMethod          = "None - clip",...
    MagneticIndexExtrapMethod = "None - clip",...
    fluxFlagsSrc              = "Dialog",...
    fluxFlags                 = "ones(1,23)",...
    useOxygen                 = "on", ...
    dragCoeffSrc              = "Dialog",...
    dragCoeff                 = '2.179',...
    dragAreaSrc               = "Dialog",...
    dragArea                  = "mission.CubeSat.A");


% THIRD BODY:
% Configure third body point mass for gravitational acceleration.
set_param(mission.CubeSat.blk, ...
    ephemerisModel      = "DE405", ...
    useEphemerisDateRange = "on", ...
    startDate           = "juliandate(2010, 1, 1)", ...
    ephemerisEndDate    = "juliandate(2030, 1, 1)", ...
    useThirdBodyGravity = "on",...
    includeSunGravity   = "on",...
    includeMoonGravity  = "on");


% SRP: 
set_param(mission.CubeSat.blk, ...
    useSRP               = "on",...
    eclipseFractionSrc   = "Dialog",...
    shadowModel          = "Dual cone",...
    reflectivityCoeffSrc = "Dialog",...
    reflectivityCoeff    = "1.8",...
    srpAreaSrc           = "Dialog",...
    srpArea              = "mission.CubeSat.A",...
    fluxPressure         = "4.5344321e-6");

% UNITS
set_param(mission.CubeSat.blk, ...
    units      = "Metric (m/s)",...
    angleUnits = "Degrees",...
    timeFormat = "Julian Date");

% For best performance and accuracy when using a numerical propagator
set_param(mission.mdl, ...
    SolverType = "Fixed-step", ...
    FixedStep  = string(mission.Timestep),...
    RelTol     = "1e-6", ...
    AbsTol     = "1e-7", ...
    StopTime   = string(seconds(mission.Duration)));

% Save model output port data as a dataset of time series objects.
set_param(mission.mdl, ...
    SaveOutput          = "on", ...
    OutputSaveName      = "yout", ...
    SaveFormat          = "Dataset",...
    DatasetSignalFormat = "timeseries");

% Run the Model and Collect Satellite Ephemerides
mission.SimOutput = sim(mission.mdl);

save([Resultspath 'SimOutput_' orbitType '.mat'],'mission');

%% Create a txt with simulator output data
spirent(mission,orbitType,Resultspath);
disp('data saved')



