
% CUBESAT MODEL WITH PERTURBATIONS CONFIGARTION FILE

clc; clear; close all; 

orbitType = 'QB50orbit';
mission.mdl = "CubesatDynamicsModel";
Resultspath = 'Data/QB50/';

% CENTRAL BODY: EARTH
% Define central body parameters
Earth.mu = 3.986*10^14;      % [m^3/s^2]
Earth.radius = 6378*10^3;    % [m]

% CUBESAT: QB50 
% Define Keplerian orbital elements
mission.CubeSat.Altitude         = 330*10^3;
mission.CubeSat.SemiMajorAxis    = Earth.radius + mission.CubeSat.Altitude; % [m]
mission.CubeSat.Eccentricity     = 0; % [-]
mission.CubeSat.Inclination      = 79; % [deg]
mission.CubeSat.RAAN             = 250;  % [deg]
mission.CubeSat.ArgOfPeriapsis   = 0; % [deg]
mission.CubeSat.TrueAnomaly      = 84; % [deg]
mission.CubeSat.ArgOfLattitude   = 0; % [deg]

% Define cubesat parameters
mission.CubeSat.m  = 2;        % [kg]
mission.CubeSat.A  = 0.01667;  % [m2]
mission.CubeSat.I  = eye(3);   % [kg/m2]


% SIMULATION
% Define StartDate and time of duration for the simulation: 1 orbit
mission.StartDate = datetime(2014, 6, 15, 12, 0, 0);
mission.Period    = 2*pi*sqrt(mission.CubeSat.SemiMajorAxis^3/Earth.mu); 
mission.Duration  = hours(mission.Period/3600);
mission.EndDate   = mission.StartDate + mission.Duration;
mission.Timestep  = 0.5;

% Open simulaiton
open_system(mission.mdl);

% SPACECRAFT DYNAMICS BLOCK
% Define the path to the Spacecraft dynamics block in the model.
mission.CubeSat.Dynamicsblk = mission.mdl + "/Spacecraft Dynamics";

% Define main properties
set_param(mission.CubeSat.Dynamicsblk, ...
    forcesin     = "off", ...
    momentsIn    = "on",...
    accelIn      = "off",...
    accelFrame   = "Fixed-frame",...
    outportFrame = "Fixed-frame",...
    outputAccel  = "on", ...
    startDate    = num2str(juliandate(mission.StartDate)), ...
    dateOut      = "on", ...
    action       = "Warning");

% Define mass properties
set_param(mission.CubeSat.Dynamicsblk, ...
    massType = "Fixed", ...
    mass     = "mission.CubeSat.m",...
    inertia  = "mission.CubeSat.I");

% Define orbit properties
set_param(mission.CubeSat.Dynamicsblk, ...
    stateFormatNum   = "Orbital elements",...
    orbitType        = "Keplerian", ...
    semiMajorAxis    = "mission.CubeSat.SemiMajorAxis", ...
    eccentricity     = "mission.CubeSat.Eccentricity", ...
    inclination      = "mission.CubeSat.Inclination", ...
    raan             = "mission.CubeSat.RAAN", ...
    argPeriapsis     = "mission.CubeSat.ArgOfPeriapsis", ...
    trueAnomaly      = "mission.CubeSat.TrueAnomaly");

% Define atittude properties
set_param(mission.CubeSat.Dynamicsblk, ...
    attitudeFrame   = "ICRF",...
    attitudeFormat  = "Quaternion",...
    attitude        = "[0.5963 -0.1096 -0.4052 0.6842]",...
    rotationOrder   = "ZYX",...
    attitudeRate    = "[0, 0, 0]",...
    outputAngAccel  = "on",...
    useGravGrad     = "on");

% Define central body properties
set_param(mission.CubeSat.Dynamicsblk, ...
    centralBody     = "Earth",...
    gravityModel    = "Spherical harmonics",...
    earthSH         = "EGM2008",...
    shDegree        = "120", ...
    useEOPs         = "on",...
    eopFile         = "aeroiersdata.mat",...
    outputTransform = "on");

% Define drag properties
set_param(mission.CubeSat.Dynamicsblk, ...
    useDrag                   = "on",...
    atmosSrc                  = "Dialog",...
    atmosModel                = "NRLMSISE-00", ...
    fluxSrc                   = "Dialog",...
    SpaceWeatherDataFile      = "aeroSpaceWeatherData.mat", ...
    F107ExtrapMethod          = "None - clip",...
    MagneticIndexExtrapMethod = "None - clip",...
    fluxFlagsSrc              = "Dialog",...
    fluxFlags                 = "ones(1,23)",...
    useOxygen                 = "on", ...
    dragCoeffSrc              = "Dialog",...
    dragCoeff                 = '2.179',...
    dragAreaSrc               = "Dialog",...
    dragArea                  = "mission.CubeSat.A");

% Define thrid-body properties
set_param(mission.CubeSat.Dynamicsblk, ...
    ephemerisModel        = "DE405", ...
    useEphemerisDateRange = "on", ...
    ephemerisstartDate  = "juliandate(2010, 1, 1)", ...
    ephemerisEndDate    = "juliandate(2030, 1, 1)", ...
    useThirdBodyGravity = "on",...
    includeSunGravity   = "on",...
    includeMoonGravity  = "on");

% Define solar radiation properties
set_param(mission.CubeSat.Dynamicsblk, ...
    useSRP               = "on",...
    eclipseFractionSrc   = "Dialog",...
    shadowModel          = "Dual cone",...
    reflectivityCoeffSrc = "Dialog",...
    reflectivityCoeff    = "1.8",...
    srpAreaSrc           = "Dialog",...
    srpArea              = "mission.CubeSat.A",...
    fluxPressure         = "4.5344321e-6");

% Define units
set_param(mission.CubeSat.Dynamicsblk, ...
    units      = "Metric (m/s)",...
    angleUnits = "Degrees",...
    timeFormat = "Julian Date");

%% ATTITUDE PROFILE BLOCK
% Define the path to the Attitude Profile block in the model.
mission.CubeSat.Attitudeblk = mission.mdl + "/Attitude Profile";

% Define parameters
set_param(mission.CubeSat.Attitudeblk, ...
    outputError         = "on",...
    outputFinalAttitude = "off",...
    portFrame           = "Fixed-Frame",...
    pointingMode = "Point at nadir",...
    tunablePointing = "off",...
    primaryAlignmentSrc = "Dialog",...
    primaryAlignment = "[0 0 1]",...
    secondaryAlignmentSrc = "Dialog",...
    secondaryAlignment = "[1 0 0]",...
    constraintFrame = "LVLH",...
    secondaryConstraintSrc = "Dialog",...
    secondaryConstraint = "[0 1 0]");

%% PROPAGATOR 
% Define propagator properties
set_param(mission.mdl, ...
    SolverType = "Fixed-step", ...
    FixedStep  = string(mission.Timestep),...
    RelTol     = "1e-6", ...
    AbsTol     = "1e-7", ...
    StopTime   = string(seconds(mission.Duration)));

% Define otuput properties
set_param(mission.mdl, ...
    SaveOutput          = "on", ...
    OutputSaveName      = "yout", ...
    SaveFormat          = "Dataset",...
    DatasetSignalFormat = "timeseries");

% RUN SIMULATION
% Run the Model and Collect CubeSat Ephemerides
mission.SimOutput = sim(mission.mdl);
save([Resultspath 'SimOutput_' orbitType '.mat'],'mission');

% Create a txt with simulator output data for Spirent
spirent(mission,orbitType,Resultspath);
disp('Spirent data saved')



